name: fcitx5-sogou
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Install rpm
        run: |
          sudo apt-get update
          sudo apt-get install rpm chrpath libarchive-tools
      - name: Build rpm
        run: |
          bash create_rpm.sh
      - name: Upload srpm and x86_64 to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*.rpm
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
